# Generated by Django 2.2.7 on 2019-11-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Level'),
        ),
    ]
