# Generated by Django 2.2.7 on 2019-11-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Skill'),
        ),
    ]
