# Generated by Django 2.2.7 on 2019-11-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191125_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Character'),
            preserve_default=False,
        ),
    ]
