# Generated by Django 2.2.7 on 2019-11-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191126_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], max_length=266, verbose_name='Ability'),
        ),
    ]
