# Generated by Django 2.2.7 on 2019-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191126_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='proficiency_bonus',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Proficiency bonus'),
        ),
    ]
