# Generated by Django 2.2.7 on 2020-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200825_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
