# Generated by Django 2.2.7 on 2020-08-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200825_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_locally_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
