# Generated by Django 2.2.7 on 2020-08-25 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_character_created_locally_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
