# Generated by Django 2.2.7 on 2020-08-25 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_character_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
