# Generated by Django 2.2.7 on 2020-09-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200825_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='created_locally_at',
            new_name='last_modified_at',
        ),
        migrations.RemoveField(
            model_name='character',
            name='updated_at',
        ),
    ]
