# Generated by Django 2.2.7 on 2020-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200904_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficiency_bonus',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Proficiency bonus'),
        ),
    ]
